version: '3.8'

services:
  frontend:
    image: ${CAPROVER_GIT_REPO_URL}/frontend:${CAPROVER_GIT_COMMIT}
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - escuela-network
    environment:
      - API_URL=https://api.tudominio.com

  app:
    image: ${CAPROVER_GIT_REPO_URL}/backend:${CAPROVER_GIT_COMMIT}
    build:
      context: ./docker/php
      args:
        user: laravel
        uid: 1000
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./storage:/var/www/storage
    networks:
      - escuela-network
    environment:
      - DB_HOST=srv-captain--tu-base-de-datos
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}

  nginx:
    image: nginx:1.19-alpine
    restart: unless-stopped
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - escuela-network

networks:
  escuela-network:
    driver: bridge
