version: "3.8"

services:
    # Servicio Frontend
    frontend:
        build:
            context: ../front-end # Ajusta esta ruta
            dockerfile: Dockerfile
        container_name: escuela-frontend
        restart: unless-stopped
        ports:
            - "8100:80"
        networks:
            - escuela-network
        depends_on:
            - nginx

    # Servicio PHP
    app:
        build:
            context: . # El contexto ser치 el directorio backend
            dockerfile: docker/php/Dockerfile
            args:
                user: laravel
                uid: 1000
        container_name: escuela-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
            - ./storage:/var/www/storage
            - ./bootstrap/cache:/var/www/bootstrap/cache
        user: root # Cambiar temporalmente a root para permisos
        entrypoint:
            [
                "/bin/sh",
                "-c",
                "chown -R laravel:www-data /var/www/storage /var/www/bootstrap/cache && docker-php-entrypoint php-fpm",
            ]

        networks:
            - escuela-network
        environment:
            - PHP_OPCACHE_VALIDATE_TIMESTAMPS=0 # Deshabilitar validaci칩n en producci칩n

    # Servicio MySQL
    db:
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        container_name: escuela-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
            # MYSQL_DATABASE: ${DB_DATABASE}
            # MYSQL_ROOT_PASSWORD: root_password # Usa la misma contrase침a que pusiste en .env
            # SERVICE_TAGS: dev
            # SERVICE_NAME: mysql
        volumes:
            - ./docker/mysql:/docker-entrypoint-initdb.d
            - ./docker/mysql/data:/var/lib/mysql
        ports:
            - "3307:3306"
        networks:
            - escuela-network

    # Servicio Nginx
    nginx:
        image: nginx:1.19-alpine
        container_name: escuela-nginx
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx:/etc/nginx/conf.d
        networks:
            - escuela-network

networks:
    escuela-network:
        driver: bridge
