name: Deploy to Production

on:
  push:
    branches: [feature/argenedisAlvarez] # o master, según tu rama principal

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install CapRover CLI
        run: npm install -g caprover

      - name: Deploy to CapRover
        env:
          CAPROVER_URL: ${{ secrets.CAPROVER_URL }}
          CAPROVER_PASSWORD: ${{ secrets.CAPROVER_PASSWORD }}
          CAPROVER_APP_NAME: ${{ secrets.CAPROVER_APP_NAME }}
        run: |
          caprover deploy \
            -h "$CAPROVER_URL" \
            -p "$CAPROVER_PASSWORD" \
            -a "$CAPROVER_APP_NAME" \
            -b main
